jdk: 
- oraclejdk7
env:
  global: 
    secure: d1kOuK3dSEs2nNZdGFNcY9KLI5PuWOv7xq9V1b+/+rzhi/BezsvEAjRw+7SeVa/sBk5LcKuKtW06Mjst0npXk487TpQpuLSNzUbX1aaTw4+oG0iJWKeK559iiMs+MBSFYvC6XPts5DkNM+hn5KmhuzCTHBotCv7ZB9Zmuj/ULsg=
  matrix: 
  - HADOOPVERSION=0.20.2
  - HADOOPVERSION=cdh3u4
  - HADOOPVERSION=cdh3u5
  - HADOOPVERSION=1.0.4
  - HADOOPVERSION=1.1.2
  - HADOOPVERSION=1.2.1
  - HADOOPVERSION=2.2.0
  - HADOOPVERSION=cdh4.2.0
  - HADOOPVERSION=cdh4.2.0 YARN=true
  - HADOOPVERSION=cdh4.3.0
  - HADOOPVERSION=cdh4.3.0 YARN=true
  - HADOOPVERSION=cdh4.4.0
  - HADOOPVERSION=cdh4.4.0 YARN=true
  - HADOOPVERSION=cdh4.5.0
  - HADOOPVERSION=cdh4.5.0 YARN=true
python: 
- "2.7"
install:
- export LD_PRELOAD=/lib/x86_64-linux-gnu/libssl.so.1.0.0
- python setup.py install
before_install: 
- sudo apt-get install build-essential python-all-dev libboost-python-dev libssl-dev
- ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
- cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
- echo NoHostAuthenticationForLocalhost=yes >> ~/.ssh/config
- sudo groupadd admin
- sudo usermod  -a -G admin $USER
- groups $USER
- . .travis/install_hadoop.sh

script:
- python test/all_tests.py
- cd examples
- ./run_all
- cd ../
language: python
